/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as PublicProjectProjectIdRouteImport } from './routes/public-project.$projectId'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as InvitationAcceptInviteIdRouteImport } from './routes/invitation/accept.$inviteId'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedInvitationsRouteImport } from './routes/_layout/_authenticated/invitations'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardInvitationsRouteImport } from './routes/_layout/_authenticated/dashboard/invitations'
import { Route as LayoutAuthenticatedDashboardWorkspaceCreateRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/create'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/general'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/program/index'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/program/week-over-week/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/program/roadmap/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/settings'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/members'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/projects/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/issues/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/program/team/$teamId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId_'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const PublicProjectProjectIdRoute = PublicProjectProjectIdRouteImport.update({
  id: '/public-project/$projectId',
  path: '/public-project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const InvitationAcceptInviteIdRoute =
  InvitationAcceptInviteIdRouteImport.update({
    id: '/invitation/accept/$inviteId',
    path: '/invitation/accept/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/_layout/_authenticated/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/_layout/_authenticated/onboarding',
    path: '/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedInvitationsRoute =
  LayoutAuthenticatedInvitationsRouteImport.update({
    id: '/_layout/_authenticated/invitations',
    path: '/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/_layout/_authenticated/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardInvitationsRoute =
  LayoutAuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceCreateRoute =
  LayoutAuthenticatedDashboardWorkspaceCreateRouteImport.update({
    id: '/workspace/create',
    path: '/workspace/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRouteImport.update(
    {
      id: '/program/',
      path: '/program/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport.update(
    {
      id: '/$projectId/workflow',
      path: '/$projectId/workflow',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport.update(
    {
      id: '/$projectId/visibility',
      path: '/$projectId/visibility',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport.update(
    {
      id: '/$projectId/integrations',
      path: '/$projectId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport.update(
    {
      id: '/$projectId/general',
      path: '/$projectId/general',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRouteImport.update(
    {
      id: '/program/week-over-week/',
      path: '/program/week-over-week/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRouteImport.update(
    {
      id: '/program/roadmap/',
      path: '/program/roadmap/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRouteImport.update(
    {
      id: '/team/$teamId/settings',
      path: '/team/$teamId/settings',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRouteImport.update(
    {
      id: '/team/$teamId/members',
      path: '/team/$teamId/members',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRouteImport.update(
    {
      id: '/team/$teamId/projects/',
      path: '/team/$teamId/projects/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRouteImport.update(
    {
      id: '/team/$teamId/issues/',
      path: '/team/$teamId/issues/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRouteImport.update(
    {
      id: '/program/team/$teamId/',
      path: '/program/team/$teamId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/wiki',
      path: '/team/$teamId/project/$projectId/wiki',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/milestones',
      path: '/team/$teamId/project/$projectId/milestones',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/gantt',
      path: '/team/$teamId/project/$projectId/gantt',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/board',
      path: '/team/$teamId/project/$projectId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/backlog',
      path: '/team/$teamId/project/$projectId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRouteImport.update(
    {
      id: '/$pageId',
      path: '/$pageId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRouteImport.update(
    {
      id: '/team/$teamId/project/$projectId/task/$taskId_',
      path: '/team/$teamId/project/$projectId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/program/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute
  '/dashboard/workspace/$workspaceId/program/roadmap/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute
  '/dashboard/workspace/$workspaceId/program/week-over-week/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute
  '/dashboard/workspace/$workspaceId/program/team/$teamId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/issues/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/projects/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteWithChildren
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device': typeof DeviceIndexRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/program': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute
  '/dashboard/workspace/$workspaceId/program/roadmap': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute
  '/dashboard/workspace/$workspaceId/program/week-over-week': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute
  '/dashboard/workspace/$workspaceId/program/team/$teamId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/issues': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/projects': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute
  '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/_layout/_authenticated/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/roadmap/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/week-over-week/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/team/$teamId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/issues/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/projects/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId_': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device/'
    | '/dashboard'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/program/'
    | '/dashboard/workspace/$workspaceId/team/$teamId/members'
    | '/dashboard/workspace/$workspaceId/team/$teamId/settings'
    | '/dashboard/workspace/$workspaceId/program/roadmap/'
    | '/dashboard/workspace/$workspaceId/program/week-over-week/'
    | '/dashboard/workspace/$workspaceId/program/team/$teamId/'
    | '/dashboard/workspace/$workspaceId/team/$teamId/issues/'
    | '/dashboard/workspace/$workspaceId/team/$teamId/projects/'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/program'
    | '/dashboard/workspace/$workspaceId/team/$teamId/members'
    | '/dashboard/workspace/$workspaceId/team/$teamId/settings'
    | '/dashboard/workspace/$workspaceId/program/roadmap'
    | '/dashboard/workspace/$workspaceId/program/week-over-week'
    | '/dashboard/workspace/$workspaceId/program/team/$teamId'
    | '/dashboard/workspace/$workspaceId/team/$teamId/issues'
    | '/dashboard/workspace/$workspaceId/team/$teamId/projects'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
    | '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/invitations'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/_layout/_authenticated/dashboard/invitations'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/projects'
    | '/_layout/_authenticated/dashboard/settings/workspace'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId'
    | '/_layout/_authenticated/dashboard/workspace/create'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/workspace/general'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/settings'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/roadmap/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/week-over-week/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/team/$teamId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/issues/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/projects/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId_'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  PublicProjectProjectIdRoute: typeof PublicProjectProjectIdRoute
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedInvitationsRoute: typeof LayoutAuthenticatedInvitationsRoute
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
  InvitationAcceptInviteIdRoute: typeof InvitationAcceptInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/public-project/$projectId': {
      id: '/public-project/$projectId'
      path: '/public-project/$projectId'
      fullPath: '/public-project/$projectId'
      preLoaderRoute: typeof PublicProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/invitation/accept/$inviteId': {
      id: '/invitation/accept/$inviteId'
      path: '/invitation/accept/$inviteId'
      fullPath: '/invitation/accept/$inviteId'
      preLoaderRoute: typeof InvitationAcceptInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/invitations': {
      id: '/_layout/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/invitations': {
      id: '/_layout/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/create': {
      id: '/_layout/_authenticated/dashboard/workspace/create'
      path: '/workspace/create'
      fullPath: '/dashboard/workspace/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/dashboard/workspace/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace': {
      id: '/_layout/_authenticated/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects': {
      id: '/_layout/_authenticated/dashboard/settings/projects'
      path: '/projects'
      fullPath: '/dashboard/settings/projects'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/dashboard/workspace/$workspaceId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/dashboard/workspace/$workspaceId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/general': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/general'
      path: '/general'
      fullPath: '/dashboard/settings/workspace/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/'
      path: '/program'
      fullPath: '/dashboard/workspace/$workspaceId/program/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
      path: '/$projectId/workflow'
      fullPath: '/dashboard/settings/projects/$projectId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
      path: '/$projectId/visibility'
      fullPath: '/dashboard/settings/projects/$projectId/visibility'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
      path: '/$projectId/integrations'
      fullPath: '/dashboard/settings/projects/$projectId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
      path: '/$projectId/general'
      fullPath: '/dashboard/settings/projects/$projectId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/week-over-week/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/week-over-week/'
      path: '/program/week-over-week'
      fullPath: '/dashboard/workspace/$workspaceId/program/week-over-week/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/roadmap/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/roadmap/'
      path: '/program/roadmap'
      fullPath: '/dashboard/workspace/$workspaceId/program/roadmap/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/settings': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/settings'
      path: '/team/$teamId/settings'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/members'
      path: '/team/$teamId/members'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/projects/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/projects/'
      path: '/team/$teamId/projects'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/issues/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/issues/'
      path: '/team/$teamId/issues'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/issues/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/team/$teamId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/program/team/$teamId/'
      path: '/program/team/$teamId'
      fullPath: '/dashboard/workspace/$workspaceId/program/team/$teamId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
      path: '/team/$teamId/project/$projectId/wiki'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
      path: '/team/$teamId/project/$projectId/milestones'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/milestones'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
      path: '/team/$teamId/project/$projectId/gantt'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
      path: '/team/$teamId/project/$projectId/board'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
      path: '/team/$teamId/project/$projectId/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
      path: '/$pageId'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/wiki/$pageId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId_'
      path: '/team/$teamId/project/$projectId/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/team/$teamId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsProjectsRouteChildren {
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsProjectsRouteChildren: LayoutAuthenticatedDashboardSettingsProjectsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsProjectsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsProjectsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren {
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
}

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren: LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute,
  }

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsProjectsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsProjectsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsWorkspaceRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiPageIdRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiIndexRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdSettingsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramRoadmapIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramWeekOverWeekIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProgramTeamTeamIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdIssuesIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectsIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBacklogRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdGanttRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdMilestonesRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdWikiRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdTeamTeamIdProjectProjectIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardInvitationsRoute: typeof LayoutAuthenticatedDashboardInvitationsRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceCreateRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardInvitationsRoute:
      LayoutAuthenticatedDashboardInvitationsRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceCreateRoute:
      LayoutAuthenticatedDashboardWorkspaceCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  PublicProjectProjectIdRoute: PublicProjectProjectIdRoute,
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedInvitationsRoute: LayoutAuthenticatedInvitationsRoute,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
  InvitationAcceptInviteIdRoute: InvitationAcceptInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
